#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers
source ./_common.sh

#=================================================
# PRE-BACKUP HOOK
#=================================================

# Stop the service to ensure data consistency
ynh_script_progression "Stopping $app's service before backup..."
ynh_systemctl_action --action=stop --service_name="$app"

#=================================================
# BACKUP FILES
#=================================================

ynh_script_progression "Backing up installation directory..."
ynh_backup --app="$app" --name="ankisync-install" "$install_dir"

ynh_script_progression "Backing up data directory..."
ynh_backup --app="$app" --name="ankisync-data" "$data_dir"

#=================================================
# POST-BACKUP HOOK
#=================================================

# Restart the service after the backup
ynh_script_progression "Restarting $app's service after backup..."
ynh_systemctl_action --action=start --service_name="$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Backup of $app completed"
