#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================
source /usr/share/yunohost/helpers
source ./_common.sh

#=================================================
# STOP AND REMOVE THE SERVICE
#=================================================
ynh_script_progression "Stopping and removing the $app service..."
ynh_systemctl_action --action=stop --service_name="$app"
yunohost service remove "$app"

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations for $app..."
ynh_remove_systemd_config
ynh_remove_nginx_config

#=================================================
# REMOVE APP DIRECTORIES
#=================================================
ynh_script_progression "Removing $app directories..."
rm -rf "$install_dir"
rm -rf "$data_dir"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Removal of $app completed"
