#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers
source ./_common.sh

#=================================================
# RESTORE FILES
#=================================================
ynh_script_progression "Restoring $app's files from backup..."

# Restore the main app directory. The path is used as the identifier.
ynh_restore_file "$install_dir"

# Restore the data directory.
ynh_restore_file "$data_dir"

#=================================================
# FIX PERMISSIONS AFTER RESTORE
#=================================================
ynh_script_progression "Updating permissions..."
chown -R "$app:$app" "$install_dir"
chmod +x "$install_dir/anki-sync-server"
chown -R "$app:$app" "$data_dir"

#=================================================
# RESTART SERVICE
#=================================================
# The systemd and nginx configs are automatically restored by yunohost core.
# We just restart the service to apply the restored configuration and data.
ynh_script_progression "Restarting $app service..."
ynh_systemctl_action --action=restart --service_name="$app"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Restoration of $app completed."
